apiVersion: v1
kind: ResourceQuota
metadata:
  name: fund-llm-budget
  namespace: fund-llm
  labels:
    app.kubernetes.io/part-of: fund-llm
spec:
  hard:
    requests.nvidia.com/gpu: '1'
    requests.storage: 20Gi
    requests.cpu: '5'
    limits.cpu: '9'
    requests.memory: 18Gi
    limits.memory: 26Gi
    pods: '3'
    persistentvolumeclaims: '1'
    services.loadbalancers: '0'
