apiVersion: v1
kind: Service
metadata:
  name: vllm
  namespace: fund-llm
  labels:
    app.kubernetes.io/part-of: fund-llm
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: vllm
  ports:
  - name: http
    port: 8000
    targetPort: http
